[package]

name = "urpc"
version = "0.0.1"
authors = ["Keegan McAllister <kmcallister@mozilla.com>"]

[dependencies]
rustc-serialize = "0"

[dev-dependencies]
unix_socket = "0"

[dependencies.bincode]
git = "https://github.com/TyOverby/bincode"
